<a href="https://colab.research.google.com/github/Rubnserrano/TF-Certification/blob/main/00_curso_tensorflow_certificate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EJERCICIOS


00.  TensorFlow Fundamentals Exercises
01.  Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
02.  Find the shape, rank and size of the tensors you created in 1.
03.  Create two tensors containing random values between 0 and 1 with shape [5, 300].
04.  Multiply the two tensors you created in 3 using matrix multiplication.
05.  Multiply the two tensors you created in 3 using dot product.
06.  Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
0.7  Find the min and max values of the tensor you created in 6 along the first axis.
0.8  Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
0.9  Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
0.10 One-hot encode the tensor you created in 9.

In [59]:
#5
muldot1 = tf.tensordot(rand1, tf.transpose(rand2), axes=1)
print(f'The dot mult between rand1 and rand2.T: \n {muldot1}')

muldot2 = tf.tensordot(tf.transpose(rand1), rand2, axes=1)
print(f'The dot mult between rand1.T and rand2: \n {muldot2}')

mul1 == muldot1,


The dot mult between rand1 and rand2.T: 
 [[ 14.913218    -0.55677366  -9.909836   -10.573011    10.969653  ]
 [  0.49515152  24.104378    11.763264     2.113676   -21.95736   ]
 [ -9.712297    -8.945776    14.049825    23.227276    21.9371    ]
 [  4.6764517   -6.168643   -25.081284   -16.319977   -49.996113  ]
 [  0.12659264 -13.628103   -15.728617   -12.990693    -6.9835596 ]]
The dot mult between rand1.T and rand2: 
 [[ 8.213633    1.0903815  -2.230025   ... -3.0854595   6.2754397
   1.9148272 ]
 [ 4.345087    0.09137577 -3.017852   ... -0.24191537  4.1908617
   0.7064656 ]
 [ 2.6816695  -3.3974175  -3.296514   ... -0.37390456  1.749292
   0.7750931 ]
 ...
 [ 1.6394053   1.0170882   0.2831524  ... -2.881369    1.9431812
   2.8533697 ]
 [-3.7893028  -2.559697   -2.8801975  ...  2.2011101  -2.4504611
  -0.7819225 ]
 [ 5.715545    2.085618   -2.4082282  ... -0.01885016  4.303542
  -1.0923401 ]]


<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [53]:
# Apunte reshape != transpose
v1 = tf.constant([[1,2],
                  [3,4],
                  [5,6]])

v2 = tf.constant([[7,8],
                  [9,10],
                  [11,12]])

v1t = tf.transpose(v2)
v1r = tf.reshape(v2, shape=(2,3))

print(f'v1 transpuesta : \n {v1t}')
print(f'v1 reshappe : \n {v1r}')

v1 transpuesta : 
 [[ 7  9 11]
 [ 8 10 12]]
v1 reshappe : 
 [[ 7  8  9]
 [10 11 12]]


In [36]:
#4
mul1 = rand1 @ tf.transpose(rand2)
print(f'Result of rand1 * rand2.T: \n {mul1}')
mul2 = tf.transpose(rand1) @ rand2
print(f'Result of rand1.T * rand1: \n {mul2}')



Result of rand1 * rand2.T: 
 [[ 14.913218    -0.55677366  -9.909836   -10.573011    10.969653  ]
 [  0.49515152  24.104378    11.763264     2.113676   -21.95736   ]
 [ -9.712297    -8.945776    14.049825    23.227276    21.9371    ]
 [  4.6764517   -6.168643   -25.081284   -16.319977   -49.996113  ]
 [  0.12659264 -13.628103   -15.728617   -12.990693    -6.9835596 ]]
Result of rand1.T * rand1: 
 [[ 8.213633    1.0903815  -2.230025   ... -3.0854595   6.2754397
   1.9148272 ]
 [ 4.345087    0.09137577 -3.017852   ... -0.24191537  4.1908617
   0.7064656 ]
 [ 2.6816695  -3.3974175  -3.296514   ... -0.37390456  1.749292
   0.7750931 ]
 ...
 [ 1.6394053   1.0170882   0.2831524  ... -2.881369    1.9431812
   2.8533697 ]
 [-3.7893028  -2.559697   -2.8801975  ...  2.2011101  -2.4504611
  -0.7819225 ]
 [ 5.715545    2.085618   -2.4082282  ... -0.01885016  4.303542
  -1.0923401 ]]


In [18]:
#3
rand1 = tf.random.Generator.from_seed(5)
rand1 = rand1.normal(shape=[5,300])

rand2 = tf.random.Generator.from_seed(10)
rand2 = rand2.normal(shape=[5,300])

print(f'first random matrix: {rand1},\n second random matrix: {rand2}')

first random matrix: [[ 1.0278524   0.27974114 -0.01347923 ...  1.2053189  -0.3511434
   0.13897082]
 [ 0.32744762 -0.3579723   1.230323   ... -0.60134953  0.455365
   0.18552932]
 [-2.0545108  -1.7917832  -0.781357   ... -0.84087443  0.8430845
  -1.0322016 ]
 [ 1.0498744   0.10989144 -0.6479687  ...  0.10615379 -0.45561165
   1.69945   ]
 [ 0.32171428  0.62645096  1.3242275  ... -0.30130875  1.0943383
   0.255803  ]],
 second random matrix: [[-0.29604465 -0.21134205  0.01063002 ... -2.286797    0.07126775
   2.3546813 ]
 [ 2.2539537  -0.8510308   0.8119971  ... -1.3636322   0.5770591
   0.30280197]
 [-3.3228774  -0.27568147  0.24829084 ...  0.6243957  -2.4371004
  -0.25115213]
 [ 1.3310204   1.3616577  -0.8285553  ...  0.46930176  1.0072736
  -0.9760802 ]
 [-1.3814136  -1.273435   -3.5026186  ...  1.5593605  -0.15954968
  -0.2978496 ]]


In [9]:
2#
shape1 = scalar.shape
rank1 = scalar.ndim
size1 = tf.size(scalar).numpy()
print(f'Shape, Rank, Size of a scalar = {shape1, rank1, size1}')

shape2 = vector.shape
rank2 = vector.ndim
size2 = tf.size(vector).numpy()
print(f'Shape, Rank, Size of a vector = {shape2, rank2, size2}')

shape3 = matrix.shape
rank3= matrix.ndim
size3 = tf.size(matrix).numpy()
print(f'Shape, Rank, Size of a matrix = {shape3, rank3, size3}')




Shape, Rank, Size of a scalar = (TensorShape([]), 0, 1)
Shape, Rank, Size of a vector = (TensorShape([2]), 1, 2)
Shape, Rank, Size of a matrix = (TensorShape([3, 3]), 2, 9)


In [29]:
#1
import tensorflow as tf
scalar = tf.constant(8)
vector = tf.constant([9,9])
matrix = tf.constant([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                       [[10,11,12],
                       [13,14,15]]])

print(scalar)
print(vector)
print(matrix)
print(tensor)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor([9 9], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]], shape=(2, 2, 3), dtype=int32)
